config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users

  resources :rooms

  resources :questions

  resources :answers

  resources :given_answers

  resources :text_answers

  resources :messages

  resources :users

  get 'roles' => 'roles#index'
  get 'types' => 'types#index'
  get 'permissions' => 'permissions#index'

  mount ActionCable.server => '/cable'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  def to_s
    return data
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/given_answer.rb
class GivenAnswer < ApplicationRecord
  belongs_to :user
  belongs_to :answer

  validates :user_id, uniqueness: {:scope => :answer_id}
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :text, presence: true, length: { minimum: 1 }

  def to_s
    return user.to_s + " - " + text
  end
end

app/models/permission.rb
class Permission < ApplicationRecord
  belongs_to :user
  belongs_to :role
  belongs_to :room
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  belongs_to :room
  belongs_to :type

  validates :title, presence: true, uniqueness: true

  def to_s
    return title
  end
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :permissions

  class << self
    def default
      new(name: "Guest")
    end

    def guest
      new(name: "Guest")
    end

    def moderator
      new(name: "Moderator")
    end

    def admin
      new(name: "Admin")
    end
  end

  def to_s
    return name
  end

end

app/models/room.rb
class Room < ApplicationRecord
  has_many :users, through: :permissions
  has_many :questions, dependent: :destroy
  has_many :messages, dependent: :destroy

  validates :name, presence: true, uniqueness: true

  attr_reader :role
  attr_writer :role

  def closed
    return !open
  end

  def to_s
    return name
  end
end

app/models/text_answer.rb
class TextAnswer < ApplicationRecord
  belongs_to :user

end

app/models/type.rb
class Type < ApplicationRecord
  has_many :questions

  class << self

    def choice
      new(name: "choice")
    end

    def multiple_choice
      new(name: "multiple choice")
    end

    def text
      new(name: "text")
    end
  end

  def to_s
    return name
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, 
         :validatable, :confirmable, :lockable,
         :authentication_keys => [:login]

  validates :username, presence: true, :uniqueness => { :case_sensitive => false }

  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true

  has_many :rooms, through: :permissions
  has_many :questions
  has_many :given_answers
  has_many :messages, dependent: :destroy
  
  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      if conditions[:username].nil?
        where(conditions).first
      else
        where(username: conditions[:username]).first
      end
    end
  end

  def to_s
    return username
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @type = Type.where(id: @question.type_id).first
    @answers = Answer.where(question_id: @question.id)

    # check if user already answered the question
    answered = false
    for a in @answers
      given_answer = GivenAnswer.where(user_id: current_user.id, answer_id: a.id)
      if (given_answer.exists?)
        answered = true
        break
      end
    end

    # if true load the given answers
    given_answers = []
    if (answered)
      for a in @answers
        given_answers.append(GivenAnswer.where(user_id: current_user.id, answer_id: a.id).first)
      end
    end

    render :json => { :question => @question, 
                      :answers => @answers, 
                      :type => @type, 
                      :answered => answered,
                      :given_answers => given_answers }
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)
    respond_to do |format|
      if @question.save
        ActionCable.server.broadcast 'questions', @question
        format.json { render json: @question }
      else
        format.json { render json: @question.errors.full_messages.to_s, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:user_id, :room_id, :type_id, :title, :text, :visible, :locked)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/permissions_helper.rb
module PermissionsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
  <div class="field">
    <%= form.label :type_id %>
    <%= form.text_field :type_id, id: :question_type_id %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :question_title %>
  </div>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text, id: :question_text %>
  </div>

  <div class="field">
    <%= form.label :visible %>
    <%= form.check_box :visible, id: :question_visible %>
  </div>

  <div class="field">
    <%= form.label :locked %>
    <%= form.check_box :locked, id: :question_locked %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Questions</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Room</th>
      <th>Type</th>
      <th>Title</th>
      <th>Text</th>
      <th>Visible</th>
      <th>Locked</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.user %></td>
        <td><%= question.room %></td>
        <td><%= question.type %></td>
        <td><%= question.title %></td>
        <td><%= question.text %></td>
        <td><%= question.visible %></td>
        <td><%= question.locked %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @question.user %>
</p>

<p>
  <strong>Room:</strong>
  <%= @question.room %>
</p>

<p>
  <strong>Type:</strong>
  <%= @question.type %>
</p>

<p>
  <strong>Title:</strong>
  <%= @question.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @question.text %>
</p>

<p>
  <strong>Visible:</strong>
  <%= @question.visible %>
</p>

<p>
  <strong>Locked:</strong>
  <%= @question.locked %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>